name: sms_autofill
description: Flutter plugin to provide SMS code autofill support
version: 1.0.0
homepage: https://github.com/SunnatilloShavkatov/sms_autofill.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pin_input_text_field: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.jaumard.smsautofill
        pluginClass: SmsAutoFillPlugin
      ios:
        pluginClass: SmsAutoFillPlugin
